const PROJECTS = [
  {
    id: 0,
    title: "Not Your Weather App",
    link: "https://notyourweather.web.app",
    isConfidential: false,
    imageURL: process.env.PUBLIC_URL + "/img/homepage/projects/nywa.webp",
    techStacks: ["React.js", "OpenWeather API"],
    description: "My first React.js project. Used OpenWeather API to fetch weather data.",
  },
  {
    id: 1,
    title: "Kembara Loka",
    link: "https://github.com/cherryplcked/ppsmb2021",
    isConfidential: false,
    imageURL: process.env.PUBLIC_URL + "/img/homepage/projects/kembara-loka.webp",
    techStacks: ["React.js", "Three.js"],
    description: "The first campus 3D map in Indonesia. Created using React.js framework and Three.js libary.",
  },
  {
    id: 2,
    title: "Rubik Karsa",
    link: "https://www.youtube.com/watch?v=3d0hfnIvFBQ",
    isConfidential: false,
    imageURL: process.env.PUBLIC_URL + "/img/homepage/projects/rubik-karsa.webp",
    techStacks: ["Arduino", "Python"],
    description: "Kinetic wall formation for Opening Ceremony of PPSMB UGM 2021. Break MURI record for Most Frame Counts for 3D Block Formation (1908 Frame Counts).",
  },
  {
    id: 3,
    title: "INA-SkinPath",
    link: null,
    isConfidential: false,
    imageURL: process.env.PUBLIC_URL + "/img/homepage/projects/INA-SkinPath.webp",
    techStacks: ["React Native", "Firebase"],
    description: "Created an Android app using React Native framework. A collaboration with Department of Dermatology and Venereology FK-KMK UGM.",
  },
  {
    id: 4,
    title: "avtcust",
    link: null,
    isConfidential: true,
    imageURL: process.env.PUBLIC_URL + "/img/homepage/projects/avtcust.webp",
    techStacks: ["Laravel", "JavaScript"],
    description: "A booking management system for cargo airlines. Customer can make bookings, top up their balance, and many more!",
  },
  {
    id: 5,
    title: "avtsys",
    link: null,
    isConfidential: true,
    imageURL: process.env.PUBLIC_URL + "/img/homepage/projects/avtsys.webp",
    techStacks: ["Laravel", "JavaScript"],
    description: "This is the admin side of the Avter System. Admin can create schedule, see monthly analytics, and many more!",
  },
  {
    id: 5,
    title: "Bus Tracker",
    link: "https://github.com/cherryplcked/bus-tracker",
    isConfidential: false,
    imageURL: process.env.PUBLIC_URL + "/img/homepage/projects/bus-tracker.webp",
    techStacks: ["STM32", "GNSS", "C"],
    description: "My bachelor thesis project. Vehicle tracker system for Trans Gadjah Mada using STM32-WL55JC1 and Teseo-LIV3FL GNSS Module.",
  },
];

export default PROJECTS;
